### ISSUE TITLE
SMTP Authentication Error - Send history to friends via email

### ISSUE THREAD

**Issue by mistryishan25** [aditicsalunkhe/Group74-CalorieApp_Server#23]
**Describe the bug**
When you try to send your calorie history to your friends it throws an authentication error

**To Reproduce**
1. Go to the `Friends` tab located at the top ribbon
2. Click on the block that says `Share data with Friends (Type friend's email ID comma separated)`
3. Type the email of the person with whom the data is to be shared and press send

**Expected behavior**
There is an email sent with your calorie data to the mentioned address.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Brave
 - 1.59.117

**Comment by WangWangIsDog** [comment]
This is a critical functionality which greatly impact user experience
